name: .NET Library CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # Update this to your .NET version

    # Optional: Setup MSBuild if you need to use it for specific build tasks
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore StatisticsCalculator.sln # Update this to your solution's name

    # Build your library
    - name: Build
      run: dotnet build StatisticsCalculator.sln --configuration ${{ matrix.configuration }} --no-restore

    # Run tests
    - name: Test
      run: dotnet test StatisticsCalculator.Tests/StatisticsCalculator.Tests.csproj --no-restore --verbosity normal
      # Update the above line with the actual path and name of your test project

    # Optional: If you want to create a NuGet package for your library
    - name: Pack
      run: dotnet pack StatisticsCalculator/StatisticsCalculator.csproj --configuration Release --no-build --output nupkgs
      # Update the above line with the actual path and name of your project

    # Optional: Upload the generated NuGet package as an artifact
    - name: Upload NuGet Package
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Packages
        path: nupkgs/*.nupkg
